tenant: "public"
namespace: "default"
name: "mongo-source"
topicName: "mongo-topic"
archive: "connectors/pulsar-io-mongo-3.2.0.nar"
parallelism: 1

configs:
  mongoUri: "mongodb://mongo1:27017/geoglify?replicaSet=rs0"
  database: "geoglify"
  collection: "ships"
  syncType: "full_sync"
