tenant: "public"
namespace: "default"
name: "mongo-test-sink"
inputs:
  - mongo-sink

configs:
  mongoUri: "mongodb://mongo1:27017/geoglify?replicaSet=rs0"
  database: "geoglify"
  collection: "shipsSync"
  syncType: "full_sync"
